/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Principal.Felinos;
import Principal.FuncBtns;
/**
 *
 * @author angeloabf
 */
public class PesquisarParentes extends javax.swing.JFrame {
    Felinos felinos = new Felinos();
    /**
     * Creates new form PesquisarParentes
     */
    public PesquisarParentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pantheraBtn = new javax.swing.JButton();
        gatoVermelhoBtn = new javax.swing.JButton();
        linceDoDesertoBtn = new javax.swing.JButton();
        gatoDomesticoBtn = new javax.swing.JButton();
        oncaPardaBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Felidaes Ancestrais");
        jLabel1.setMaximumSize(new java.awt.Dimension(182, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(182, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(182, 32));

        pantheraBtn.setText("Panthera");
        pantheraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantheraBtnActionPerformed(evt);
            }
        });

        gatoVermelhoBtn.setText("Gato-Vermelho");
        gatoVermelhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoVermelhoBtnActionPerformed(evt);
            }
        });

        linceDoDesertoBtn.setText("Lince do deserto");
        linceDoDesertoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linceDoDesertoBtnActionPerformed(evt);
            }
        });

        gatoDomesticoBtn.setText("Gato domestico");
        gatoDomesticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoDomesticoBtnActionPerformed(evt);
            }
        });

        oncaPardaBtn.setText("Onça-Parda");
        oncaPardaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncaPardaBtnActionPerformed(evt);
            }
        });

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linceDoDesertoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(pantheraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gatoVermelhoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oncaPardaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(gatoDomesticoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarBtn)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gatoVermelhoBtn)
                    .addComponent(linceDoDesertoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pantheraBtn)
                    .addComponent(oncaPardaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gatoDomesticoBtn)
                .addGap(78, 78, 78)
                .addComponent(voltarBtn)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(396, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        new FuncBtns().voltar();
        this.dispose();
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void pantheraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantheraBtnActionPerformed
        felinos.pantheraAncestral();
        felinos.imprimeRelacionados("PANTHERA ANCESTRAL");
    }//GEN-LAST:event_pantheraBtnActionPerformed

    private void gatoDomesticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoDomesticoBtnActionPerformed
        felinos.gatoDomestico();
        felinos.imprimeRelacionados("GATO DOMÉSTICO ANCESTRAL");
    }//GEN-LAST:event_gatoDomesticoBtnActionPerformed

    private void linceDoDesertoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linceDoDesertoBtnActionPerformed
        felinos.linceDoDesertoAncestral();
        felinos.imprimeRelacionados("LINCE DO DESERTO ANCESTRAL");
    }//GEN-LAST:event_linceDoDesertoBtnActionPerformed

    private void gatoVermelhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoVermelhoBtnActionPerformed
        felinos.gatoVermelhoAncestral();
        felinos.imprimeRelacionados("GATO VERMELHO ANCESTRAL");
    }//GEN-LAST:event_gatoVermelhoBtnActionPerformed

    private void oncaPardaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncaPardaBtnActionPerformed
        felinos.oncaPardaAncestral();
        felinos.imprimeRelacionados("ONÇA PARDA ANCESTRAL");
    }//GEN-LAST:event_oncaPardaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarParentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarParentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarParentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarParentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarParentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gatoDomesticoBtn;
    private javax.swing.JButton gatoVermelhoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton linceDoDesertoBtn;
    private javax.swing.JButton oncaPardaBtn;
    private javax.swing.JButton pantheraBtn;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
